#! /usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# Start and stop links
service_link_enhanced("sme9admind", "S99", "7");
service_link_enhanced("sme9admind", "K97", "6");
service_link_enhanced("sme9admind", "K20", "0");
service_link_enhanced("sme9admind", "K20", "1");


# Start and stop links to lm_sensors
service_link_enhanced("lm_sensors", "S99", "7");

# Links for the panel
panel_link("sme9admin", "manager");
#system("mkdir -p root/etc/e-smith/web/panels/manager/html/sme9admin");
safe_symlink("/etc/e-smith/web/panels/manager/html/sme9admin", "root/etc/e-smith/web/panels/user/html/sme9admin");

# Logrotate
event_link("sme9admin-parselog","logrotate","15");
#Creation of the event sme9admin-update
for my $event (qw(
     sme9admin-update
    ))
    
    {
    safe_symlink("start", "root/etc/e-smith/events/$event/services2adjust/mysql.init");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/sme9admind");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/lm_sensors");
    }
#integration of event for console-save & bootstrap-console-save
for my $event (qw(
      console-save
    ))

    {
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/sme9admind");
    safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/lm_sensors");
    }

