#!/bin/bash

# mysql
if [ -d /var/lib/mysql/sme7admin ] && [ ! -d /var/lib/mysql/sme8admin ]; then
    echo "Migrating existing sme7admin MySQL database."
    mysqladmin create sme8admin
    mysqldump sme7admin | mysql sme8admin
    PASS=$(/sbin/e-smith/db configuration getprop sme8admind DbPassword)
    mysql -e " grant all privileges on sme8admin.* to 'sme8admin'@'localhost' identified by '$PASS'"
    mysqladmin flush-privileges
elif [ -e /var/lib/mysql/sme8admin ]; then
    # c'est une mise jour, on fait une upgrade de la base si besoin
    sh /usr/share/doc/smeserver-sme8admin/update-mysql.sh
else
    #si c'est une freshinstall on cree la bd mysql
    sh /usr/share/doc/smeserver-sme8admin/create-mysql.sh
fi

# rrd
if [ -d /var/lib/sme7admin ] && [ ! -d /var/lib/sme8admin ]; then
    echo "Migrating existing sme6admin RRDs files."
    cp -vr /var/lib/sme7admin /var/lib/sme8admin
elif [ -d /var/lib/sme8admin ]; then
    # c'est une upgrade, rien de particulier a faire
    echo ''
else
    #si c'est une freshinstall on cree les rrd
    sh /usr/share/doc/smeserver-sme8admin/create-rrd.sh
fi
