#!/usr/bin/perl -w
# Sme9admin - evenement appele par logrotate
# Copyright (C) 2006
# This file is distributed under the GPL license.
# Landry Breuil <landry@firewall-services.com>, 2006.

#------------------------------------------------------------
# On envoie le signal SIGUSR1 a sme9admind pour qu'il parse les logs 
#------------------------------------------------------------

exec("/usr/bin/killall", "-USR1", "sme9admind");
# NOTREACHED
die("Failed to exec /usr/bin/killall -USR1 sme9admind");
